const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("fs");
const path = require("path");
const YAML = require("yaml");
const { spawnSync } = require("child_process");
const root = path.resolve(__dirname, "..");

test("OpenAPI, routes, Postman JSON, and secret scan validate", () => {
  const result = spawnSync(process.execPath, [path.join(root, "scripts", "validateDocumentation.js")], { cwd: root, encoding: "utf8" });
  assert.equal(result.status, 0, result.stderr || result.stdout);
  assert.equal(JSON.parse(result.stdout).operations, 60);
});
test("OpenAPI schemas and bearer authentication parse", () => { const spec = YAML.parse(fs.readFileSync(path.join(root, "docs", "openapi.yaml"), "utf8")); assert.equal(spec.openapi, "3.0.3"); assert.equal(spec.components.securitySchemes.BearerAuth.scheme, "bearer"); assert.ok(spec.components.schemas.Pagination); assert.ok(spec.components.schemas.ValidationError); });
test("all required API tags exist", () => { const spec = YAML.parse(fs.readFileSync(path.join(root, "docs", "openapi.yaml"), "utf8")); const tags = new Set(spec.tags.map((tag) => tag.name)); for (const name of ["Health", "Authentication", "Users", "Institutions", "Students", "Credentials", "Public Verification", "Verification Logs", "Audit Logs", "Dashboard", "QR Codes", "Generated Certificates", "Blockchain Administration"]) assert.ok(tags.has(name), name); });
test("all requested reusable schemas exist", () => { const schemas = YAML.parse(fs.readFileSync(path.join(root, "docs", "openapi.yaml"), "utf8")).components.schemas; for (const name of ["StandardSuccessResponse", "StandardErrorResponse", "ValidationErrorResponse", "PaginationMetadata", "User", "SafeUserProfile", "Institution", "Student", "Credential", "VerificationResult", "VerificationLog", "AuditLog", "DashboardSummary", "DashboardTrendPoint", "SystemHealth", "QRCodeResponse", "GeneratedCertificateResponse", "VerificationMethod"]) assert.ok(schemas[name], name); });
test("multipart field contracts match implemented middleware", () => { const paths = YAML.parse(fs.readFileSync(path.join(root, "docs", "openapi.yaml"), "utf8")).paths; const issue = paths["/api/credentials/issue"].post.requestBody.content["multipart/form-data"].schema; assert.deepEqual(issue.required, ["certificate", "studentId", "institutionId", "qualification", "issueDate"]); const verify = paths["/api/verify/file"].post.requestBody.content["multipart/form-data"].schema; assert.ok(verify.required.includes("certificate")); assert.equal(issue.properties.certificate.format, "binary"); });
test("public operations do not mandate bearer and protected operations do", () => { const paths = YAML.parse(fs.readFileSync(path.join(root, "docs", "openapi.yaml"), "utf8")).paths; assert.equal(paths["/health"].get.security, undefined); assert.equal(paths["/api/auth/login"].post.security, undefined); assert.equal(paths["/api/auth/forgot-password"].post.security, undefined); assert.equal(paths["/api/auth/reset-password"].post.security, undefined); assert.equal(paths["/api/verify/hash/{hash}"].get.security, undefined); assert.deepEqual(paths["/api/users"].get.security, [{ BearerAuth: [] }]); assert.deepEqual(paths["/api/dashboard/system-health"].get.security, [{ BearerAuth: [] }]); });
test("Postman collection and environment are importable JSON", () => { for (const file of ["Zimbabwe-Skill-Verification-Platform.postman_collection.json", "Local.postman_environment.json"]) assert.doesNotThrow(() => JSON.parse(fs.readFileSync(path.join(root, "docs", "postman", file), "utf8"))); });
test("Postman login captures token and uses placeholders", () => { const collection = JSON.parse(fs.readFileSync(path.join(root, "docs", "postman", "Zimbabwe-Skill-Verification-Platform.postman_collection.json"), "utf8")); const auth = collection.item.find((folder) => folder.name === "Authentication"); const login = auth.item.find((request) => request.name === "Login"); assert.match(JSON.stringify(login.event), /environment\.set\('token'/); assert.match(login.request.body.raw, /<PASSWORD>/); });
test("Postman contains thirteen isolated folders", () => { const collection = JSON.parse(fs.readFileSync(path.join(root, "docs", "postman", "Zimbabwe-Skill-Verification-Platform.postman_collection.json"), "utf8")); assert.equal(collection.item.length, 13); assert.ok(collection.item.some((folder) => folder.name === "Blockchain Administration")); });
test("Swagger UI and raw OpenAPI load when enabled", async () => { process.env.ENABLE_SWAGGER = "true"; delete require.cache[require.resolve("../backend/routes/docsRoutes")]; delete require.cache[require.resolve("../backend/app")]; const app = require("../backend/app").createApp(); const server = await new Promise((resolve) => { const instance = app.listen(0, "127.0.0.1", () => resolve(instance)); }); try { const response = await fetch(`http://127.0.0.1:${server.address().port}/api/docs/`); assert.equal(response.status, 200); assert.match(await response.text(), /swagger-ui/i); const raw = await fetch(`http://127.0.0.1:${server.address().port}/api/docs/openapi.yaml`); assert.equal(raw.status, 200); assert.match(await raw.text(), /^openapi: 3\.0\.3/m); } finally { await new Promise((resolve) => server.close(resolve)); } });
test("Swagger is controlled when disabled in production", async () => { const oldNode = process.env.NODE_ENV; process.env.NODE_ENV = "production"; process.env.ENABLE_SWAGGER = "false"; delete require.cache[require.resolve("../backend/routes/docsRoutes")]; const router = require("../backend/routes/docsRoutes"); const layer = router.stack.find((entry) => !entry.route); assert.ok(layer); process.env.NODE_ENV = oldNode; });
