const test = require("node:test"); const assert = require("node:assert/strict"); const fs = require("fs"); const path = require("path"); const YAML = require("yaml");
const root = path.resolve(__dirname, ".."); const read = (name) => fs.readFileSync(path.join(root, ".github/workflows", name), "utf8"); const parse = (name) => YAML.parse(read(name));
test("all Stage 27 workflows parse and declare permissions",()=>{for(const name of ["ci.yml","e2e.yml","security.yml","docker.yml","release.yml","deploy.yml"]){const workflow=parse(name);assert.ok(workflow.jobs);assert.ok(workflow.permissions,name);}});
test("actions use exact release tags",()=>{for(const name of fs.readdirSync(path.join(root,".github/workflows"))){assert.doesNotMatch(read(name),/uses:\s*[^\s]+@(?:main|master|v\d+)(?:\s|$)/m,name);}});
test("pull requests cannot publish or deploy",()=>{assert.match(read("docker.yml"),/github\.event_name != 'pull_request'/);assert.doesNotMatch(read("deploy.yml"),/pull_request/);assert.doesNotMatch(read("deploy.yml"),/push:/);});
test("deployment is manual, dry-run, environment protected, and fork safe",()=>{const source=read("deploy.yml");assert.match(source,/workflow_dispatch/);assert.match(source,/environment:/);assert.match(source,/DRY_RUN:/);assert.match(source,/github\.repository_owner == github\.actor|github\.event\.repository\.fork == false/);});
test("CI uses PostgreSQL 18, isolated test names, Hardhat 31337, and mocked IPFS",()=>{const source=read("e2e.yml");assert.match(source,/postgres:18\.0-bookworm/);assert.match(source,/skill_verification_ci_test/);assert.match(source,/BLOCKCHAIN_CHAIN_ID:\s*31337/);assert.match(source,/IPFS_ENABLED:\s*["']?false/);});
test("release tags are semantic and publishing is not a PR path",()=>{const source=read("release.yml");assert.match(source,/v\*\.\*\.\*/);assert.match(source,/packages:\s*write/);assert.doesNotMatch(source,/pull_request/);});
test("only real package scripts are invoked",()=>{const scripts=require("../package.json").scripts;for(const name of fs.readdirSync(path.join(root,".github/workflows"))){for(const match of read(name).matchAll(/npm run ([\w:-]+)/g))assert.ok(scripts[match[1]],`${name}: ${match[1]}`);}});
