const test = require("node:test");
const assert = require("node:assert/strict");
const schemas = require("../backend/validators/dashboardValidator");

test("trend defaults to 30 days grouped by day", () => assert.deepEqual(schemas.trend.parse({}), { period: "30days", groupBy: "day" }));
for (const groupBy of ["day", "week", "month"]) test(`${groupBy} grouping validates`, () => assert.equal(schemas.trend.safeParse({ groupBy }).success, true));
test("arbitrary groupBy is rejected", () => assert.equal(schemas.trend.safeParse({ groupBy: "year; DROP TABLE users" }).success, false));
test("invalid and reversed analytics dates are rejected", () => { assert.equal(schemas.trend.safeParse({ dateFrom: "bad" }).success, false); assert.equal(schemas.trend.safeParse({ dateFrom: "2026-02-02", dateTo: "2026-02-01" }).success, false); });
test("analytics ranges over 24 months are rejected", () => assert.equal(schemas.trend.safeParse({ dateFrom: "2020-01-01", dateTo: "2026-01-01" }).success, false));
test("verification methods are controlled", () => { for (const method of schemas.METHODS) assert.equal(schemas.verificationTrend.safeParse({ method }).success, true); assert.equal(schemas.verificationTrend.safeParse({ method: "sql" }).success, false); });
test("top institution limit is bounded at 50", () => { assert.equal(schemas.topInstitutions.parse({}).limit, 10); assert.equal(schemas.topInstitutions.safeParse({ limit: 51 }).success, false); });
test("top institution sort is whitelisted", () => { assert.equal(schemas.topInstitutions.safeParse({ sortBy: "totalStudents" }).success, true); assert.equal(schemas.topInstitutions.safeParse({ sortBy: "name DESC;--" }).success, false); });
test("recent activity default and maximum limits are enforced", () => { assert.equal(schemas.recentActivity.parse({}).limit, 10); assert.equal(schemas.recentActivity.safeParse({ limit: 51 }).success, false); });
test("failure categories and pagination are controlled", () => { assert.equal(schemas.failures.safeParse({ category: "blockchain", page: 2, limit: 50 }).success, true); assert.equal(schemas.failures.safeParse({ category: "secret" }).success, false); });

const loadDashboardModel = () => {
  const poolPath = require.resolve("../backend/config/database"); const modelPath = require.resolve("../backend/models/dashboardModel"); delete require.cache[poolPath]; delete require.cache[modelPath];
  const calls = []; const pool = { query: async (sql, values = []) => { calls.push({ sql: String(sql), values }); if (/GROUP BY.*category/s.test(sql)) return { rows: [] }; if (/COUNT\(\*\)::int total FROM audit_logs/.test(sql)) return { rows: [{ total: 0 }] }; if (/reconciliation_required/.test(sql)) return { rows: [{ failed_with_transaction: 0, active_missing_cid: 0, active_missing_transaction: 0, reconciliation_required: 0 }] }; if (/COUNT/.test(sql) && !/GROUP BY/.test(sql)) return { rows: [{ total: 0, active: 0, inactive: 0, pending: 0, processing: 0, failed: 0, revoked: 0, verified: 0, unknown: 0, inconsistency: 0 }] }; return { rows: [] }; } };
  require.cache[poolPath] = { id: poolPath, filename: poolPath, loaded: true, exports: pool };
  return { model: require(modelPath), calls };
};
test("summary uses PostgreSQL aggregate FILTER queries", async () => { const { model, calls } = loadDashboardModel(); const result = await model.getSummary(); assert.equal(result.credentials.total, 0); assert.ok(calls.every((call) => /COUNT\(/.test(call.sql))); assert.ok(calls.some((call) => /FILTER/.test(call.sql))); });
test("institution summary scope is inside each SQL query", async () => { const { model, calls } = loadDashboardModel(); await model.getSummary({ institutionId: "institution-1" }); assert.ok(calls.every((call) => call.values.includes("institution-1"))); assert.ok(calls.some((call) => /institution_id = \$1/.test(call.sql))); });
for (const groupBy of ["day", "week", "month"]) test(`credential ${groupBy} trend uses whitelisted date_trunc`, async () => { const { model, calls } = loadDashboardModel(); await model.getCredentialTrends({ dateFrom: "2026-01-01", dateTo: "2026-02-01", groupBy }); assert.match(calls[0].sql, new RegExp(`date_trunc\\('${groupBy}'`)); });
test("credential trend rejects raw dynamic grouping", async () => { const { model } = loadDashboardModel(); await assert.rejects(() => model.getCredentialTrends({ dateFrom: "2026-01-01", dateTo: "2026-02-01", groupBy: "day'); DROP TABLE users;--" }), /Unsupported/); });
test("verification trend applies method and institution as values", async () => { const { model, calls } = loadDashboardModel(); await model.getVerificationTrends({ institutionId: "institution-1", dateFrom: "2026-01-01", dateTo: "2026-02-01", groupBy: "week", method: "file" }); assert.deepEqual(calls[0].values, ["2026-01-01", "2026-02-01", "institution-1", "file"]); assert.equal(calls[0].sql.includes("institution-1"), false); });
test("top institutions uses bounded aggregate CTEs", async () => { const { model, calls } = loadDashboardModel(); await model.getTopInstitutions({ limit: 10, dateFrom: "2026-01-01", dateTo: "2026-02-01", sortBy: "totalCredentials" }); assert.match(calls[0].sql, /WITH student_counts/); assert.match(calls[0].sql, /LIMIT \$3/); });
test("top institutions rejects raw sort fragments", async () => { const { model } = loadDashboardModel(); await assert.rejects(() => model.getTopInstitutions({ limit: 10, dateFrom: "2026-01-01", dateTo: "2026-02-01", sortBy: "total_credentials; DROP TABLE users" }), /Unsupported/); });
test("most verified query excludes hashes and is bounded", async () => { const { model, calls } = loadDashboardModel(); await model.getMostVerifiedCredentials({ limit: 10, dateFrom: "2026-01-01", dateTo: "2026-02-01" }); assert.match(calls[0].sql, /LIMIT \$3/); assert.doesNotMatch(calls[0].sql, /certificate_hash/); });
test("failure analytics returns only safe event fields", async () => { const { model, calls } = loadDashboardModel(); const result = await model.getFailures({ dateFrom: "2026-01-01", dateTo: "2026-02-01", limit: 20, offset: 0 }); assert.equal(result.total, 0); assert.doesNotMatch(calls.at(-1).sql, /details|processing_error/); });
test("reconciliation analytics is SELECT-only", async () => { const { model, calls } = loadDashboardModel(); await model.getReconciliationMetrics({ institutionId: "institution-1" }); assert.match(calls[0].sql, /^SELECT/); assert.doesNotMatch(calls[0].sql, /UPDATE|DELETE|INSERT/); });
test("recent activity is bounded newest-first", async () => { const { model, calls } = loadDashboardModel(); await model.getRecentActivity({ limit: 10 }); assert.match(calls[0].sql, /ORDER BY audit_logs\.created_at DESC/); assert.match(calls[0].sql, /LIMIT \$1/); });

const loadService = () => {
  const paths = { service: require.resolve("../backend/services/dashboardService"), model: require.resolve("../backend/models/dashboardModel"), health: require.resolve("../backend/services/healthService"), audit: require.resolve("../backend/models/auditModel") };
  Object.values(paths).forEach((path) => delete require.cache[path]); const calls = [];
  const model = { getSummary: async (input) => (calls.push(["summary", input]), { verifications: { total: 0 } }), getRecentActivity: async () => [], getCredentialTrends: async (input) => (calls.push(["credential", input]), []), getVerificationTrends: async (input) => (calls.push(["verification", input]), []), getTopInstitutions: async () => [], getMostVerifiedCredentials: async () => [{ credential_id: "c", student_number: "STUDENT123", qualification: "Q" }], getFailures: async () => ({ counts: [], total: 0, rows: [] }), getReconciliationMetrics: async () => ({ failed_with_transaction: 0, active_missing_cid: 0, active_missing_transaction: 0, reconciliation_required: 0 }) };
  require.cache[paths.model] = { id: paths.model, filename: paths.model, loaded: true, exports: model }; require.cache[paths.health] = { id: paths.health, filename: paths.health, loaded: true, exports: { databaseHealth: async () => ({ status: "healthy" }), ipfsHealth: async () => ({ status: "unavailable" }), blockchainHealth: async () => ({ status: "healthy", network: "localhost", chainId: 31337 }) } }; require.cache[paths.audit] = { id: paths.audit, filename: paths.audit, loaded: true, exports: { sanitiseDetails: (value) => value } };
  return { service: require(paths.service), calls };
};
const users = { super_admin: { role: "super_admin", institutionId: null }, institution_admin: { role: "institution_admin", institutionId: "inst" }, issuer: { role: "issuer", institutionId: "inst" }, verifier: { role: "verifier", institutionId: "inst" } };
for (const role of Object.keys(users)) test(`${role} summary passes current database scope and permissions`, async () => { const { service, calls } = loadService(); await service.summary(users[role]); const options = calls[0][1]; assert.equal(options.institutionId, role === "super_admin" ? null : "inst"); assert.equal(options.includeAdministration, ["super_admin", "institution_admin"].includes(role)); assert.equal(options.includeOperations, role !== "verifier"); });
test("trend range defaults are bounded and UTC dates", () => { const { service } = loadService(); const range = service.resolveRange({ period: "7days" }); assert.match(range.dateFrom, /^\d{4}-\d{2}-\d{2}$/); assert.match(range.dateTo, /^\d{4}-\d{2}-\d{2}$/); });
test("most verified credential masks student number and removes original", async () => { const { service } = loadService(); const rows = await service.mostVerifiedCredentials({ limit: 10, period: "30days" }, users.institution_admin); assert.match(rows[0].maskedStudentNumber, /\*/); assert.equal(rows[0].student_number, undefined); });
test("health overall degrades safely when IPFS unavailable", async () => { const { service } = loadService(); const result = await service.systemHealth(); assert.equal(result.overall, "degraded"); assert.equal(JSON.stringify(result).includes("RPC"), false); assert.equal(result.blockchain.contractAvailable, true); });
test("failure response has zero-safe pagination", async () => { const { service } = loadService(); const result = await service.failures({ page: 1, limit: 20, period: "30days" }, users.institution_admin); assert.equal(result.pagination.totalPages, 0); assert.deepEqual(result.counts, {}); });

test("dashboard routes enforce role policy", () => { const router = require("../backend/routes/dashboardRoutes"); const get = (path) => router.stack.find((layer) => layer.route?.path === path).route.stack[0].handle; for (const path of ["/top-institutions", "/system-health"]) { for (const role of ["institution_admin", "issuer", "verifier"]) { const out = {}; get(path)({ user: { role } }, { status(code) { out.status = code; return this; }, json() {} }, () => { out.next = true; }); assert.equal(out.status, 403); } } });
test("verifier is denied failure analytics", () => { const router = require("../backend/routes/dashboardRoutes"); const guard = router.stack.find((layer) => layer.route?.path === "/failures").route.stack[0].handle; const out = {}; guard({ user: { role: "verifier" } }, { status(code) { out.status = code; return this; }, json() {} }, () => {}); assert.equal(out.status, 403); });
test("all dashboard routes remain authentication protected", async () => { const router = require("../backend/routes/dashboardRoutes"); const authenticate = router.stack[0].handle; const out = {}; await authenticate({ headers: {} }, { status(code) { out.status = code; return this; }, json() {} }, () => {}); assert.equal(out.status, 401); });
