const test = require("node:test");
const assert = require("node:assert/strict");
const express = require("express");
const { registry, metrics } = require("../backend/utils/metrics");
const { metricsMiddleware } = require("../backend/middleware/metricsMiddleware");
test("metrics use bounded labels and counters increment", async () => { metrics.credentialsIssued.inc({ result: "success" }); metrics.verificationResults.inc({ result: "valid" }); const text = await registry.metrics(); assert.match(text, /credentials_issued_total\{result="success"\}/); assert.match(text, /verification_results_total\{result="valid"\}/); for (const forbidden of ["email", "user_id", "student_number", "credential_hash", "transaction_hash", "institution_name"]) assert.equal(text.includes(forbidden), false); });
test("request and error counters increment", async () => { const app = express(); app.use(metricsMiddleware); app.get("/failure", (_req, res) => res.status(500).end()); const server = app.listen(0, "127.0.0.1"); await new Promise((resolve) => server.once("listening", resolve)); try { await fetch(`http://127.0.0.1:${server.address().port}/failure`); const text = await registry.metrics(); assert.match(text, /http_requests_total/); assert.match(text, /http_errors_total/); } finally { await new Promise((resolve) => server.close(resolve)); } });
test("metrics endpoint is disabled by default", async () => { const old = process.env.ENABLE_METRICS; delete process.env.ENABLE_METRICS; const app = express(); app.use("/metrics", require("../backend/routes/metricsRoutes")); const server = app.listen(0, "127.0.0.1"); await new Promise((resolve) => server.once("listening", resolve)); try { assert.equal((await fetch(`http://127.0.0.1:${server.address().port}/metrics`)).status, 404); } finally { process.env.ENABLE_METRICS = old; await new Promise((resolve) => server.close(resolve)); } });
test("enabled metrics endpoint remains protected", async () => { const old = process.env.ENABLE_METRICS; process.env.ENABLE_METRICS = "true"; const app = express(); app.use("/metrics", require("../backend/routes/metricsRoutes")); const server = app.listen(0, "127.0.0.1"); await new Promise((resolve) => server.once("listening", resolve)); try { assert.equal((await fetch(`http://127.0.0.1:${server.address().port}/metrics`)).status, 401); } finally { process.env.ENABLE_METRICS = old; await new Promise((resolve) => server.close(resolve)); } });
