const test=require("node:test");const assert=require("node:assert/strict");
const recovery=require("../backend/services/passwordRecoveryService");
const {deliverPasswordReset}=require("../backend/services/emailService");

const strong="NewSecurePass1!";
const user={id:"user-1",email:"person@example.test",institution_id:"inst-1",is_active:true,password_hash:"old-hash"};
const deps=(overrides={})=>{const calls={};return{calls,model:{findUserByEmail:async()=>user,setPasswordRecoveryToken:async(...a)=>calls.stored=a,findUserByValidResetTokenHash:async()=>user,consumePasswordRecoveryToken:async(...a)=>(calls.consumed=a,{id:user.id})},bcrypt:{compare:async()=>false,hash:async(p,c)=>(calls.hash=[p,c],"new-hash")},audit:async(e)=>calls.audit=e,...overrides}};

test("recovery tokens are CSPRNG URL-safe values and only SHA-256 hashes are persisted",async()=>{const d=deps();const result=await recovery.preparePasswordReset(user.email,d);assert.match(result.raw,/^[A-Za-z0-9_-]{43}$/);assert.match(d.calls.stored[1],/^[a-f0-9]{64}$/);assert.notEqual(d.calls.stored[1],result.raw);assert.equal(JSON.stringify(d.calls.audit).includes(result.raw),false);const ttl=new Date(d.calls.stored[2]).getTime()-Date.now();assert.ok(ttl>29*60000&&ttl<=30*60000);});
test("unknown and inactive accounts do not persist or audit reset state",async()=>{for(const candidate of [undefined,{...user,is_active:false}]){const d=deps();d.model.findUserByEmail=async()=>candidate;assert.equal(await recovery.preparePasswordReset(user.email,d),null);assert.equal(d.calls.stored,undefined);assert.equal(d.calls.audit,undefined);}});
test("valid reset hashes the token, uses bcrypt cost 12, and consumes atomically",async()=>{const d=deps();const raw=recovery.createToken();await recovery.completePasswordReset({token:raw,password:strong},d);assert.equal(d.calls.hash[1],12);assert.equal(d.calls.consumed[1],recovery.tokenHash(raw));assert.equal(d.calls.consumed[2],"new-hash");assert.equal(JSON.stringify(d.calls.audit).includes(raw),false);});
test("invalid, expired, or already-used links share one safe error",async()=>{const d=deps();d.model.findUserByValidResetTokenHash=async()=>undefined;await assert.rejects(()=>recovery.completePasswordReset({token:recovery.createToken(),password:strong},d),e=>e.code==="INVALID_PASSWORD_RESET_TOKEN");});
test("password reuse and weak passwords are rejected",async()=>{const d=deps();d.bcrypt.compare=async()=>true;await assert.rejects(()=>recovery.completePasswordReset({token:recovery.createToken(),password:strong},d),e=>e.code==="PASSWORD_REUSE");await assert.rejects(()=>recovery.completePasswordReset({token:recovery.createToken(),password:"weak"},deps()),e=>e.code==="WEAK_PASSWORD");});
test("development capture exposes reset URL only to an explicit capture callback",async()=>{const previous={node:process.env.NODE_ENV,provider:process.env.EMAIL_PROVIDER};process.env.NODE_ENV="development";process.env.EMAIL_PROVIDER="capture";let captured;const result=await deliverPasswordReset({email:user.email,resetUrl:"http://localhost/reset?token=secret"},{capture:async value=>captured=value});assert.equal(result.delivered,true);assert.equal(captured.email,user.email);process.env.NODE_ENV=previous.node;process.env.EMAIL_PROVIDER=previous.provider;});
test("production rejects development capture delivery",async()=>{const previous={node:process.env.NODE_ENV,provider:process.env.EMAIL_PROVIDER};process.env.NODE_ENV="production";process.env.EMAIL_PROVIDER="capture";await assert.rejects(()=>deliverPasswordReset({email:user.email,resetUrl:"https://example.test/reset"}),e=>e.code==="EMAIL_PROVIDER_INVALID");process.env.NODE_ENV=previous.node;process.env.EMAIL_PROVIDER=previous.provider;});
test("database consumption revokes sessions and clears recovery and lock state",()=>{const source=require("fs").readFileSync(require.resolve("../backend/models/userModel"),"utf8");for(const fragment of ["password_reset_token_hash = NULL","password_reset_expires_at = NULL","token_version = token_version + 1","failed_login_attempts = 0","locked_until = NULL","must_change_password = FALSE"])assert.ok(source.includes(fragment),fragment);});
test("public routes use dedicated limiting, strict schemas, and never require authentication",()=>{const source=require("fs").readFileSync(require.resolve("../backend/routes/authRoutes"),"utf8");assert.match(source,/forgot-password.*, passwordResetLimiter/);assert.match(source,/reset-password.*, passwordResetLimiter/);assert.ok(!/forgot-password.*authenticate/.test(source));});
