const test=require("node:test");const assert=require("node:assert/strict");
const ID="11111111-1111-4111-8111-111111111111",INST="22222222-2222-4222-8222-222222222222",OTHER="33333333-3333-4333-8333-333333333333";
const base={id:ID,student_number:"ST-001",full_name:"Student One",email:"student@example.test",programme:"Engineering",institution_id:INST,institution_name:"Example Institution",created_at:new Date()};
function load(overrides={}){const paths={controller:require.resolve("../backend/controllers/studentController"),model:require.resolve("../backend/models/studentModel"),institution:require.resolve("../backend/models/institutionModel"),audit:require.resolve("../backend/models/auditModel")};Object.values(paths).forEach(p=>delete require.cache[p]);const state={audits:[],updates:[]};const model={createStudent:async x=>({...base,...x}),getAllStudents:async()=>[base],getStudentsByInstitution:async()=>[base],getStudentById:async()=>overrides.student===null?null:{...base,...overrides.student},updateStudent:async(id,x)=>(state.updates.push(x),{...base,id,student_number:x.studentNumber,full_name:x.fullName,email:x.email,programme:x.programme}),studentHasCredentials:async()=>Boolean(overrides.hasCredentials),reassignStudentInstitution:async(id,institutionId)=>(state.updates.push({institutionId}),{...base,id,institution_id:institutionId}),...overrides.model};require.cache[paths.model]={id:paths.model,filename:paths.model,loaded:true,exports:model};require.cache[paths.institution]={id:paths.institution,filename:paths.institution,loaded:true,exports:{getInstitutionById:async()=>overrides.institution===null?null:{id:OTHER,status:overrides.institutionActive!==false}}};require.cache[paths.audit]={id:paths.audit,filename:paths.audit,loaded:true,exports:{createAuditLog:async e=>state.audits.push(e)}};return{controller:require(paths.controller),state}};
async function invoke(handler,{role="super_admin",institutionId=null,body={},params={id:ID},query={}}={}){const out={};const req={user:{role,institutionId,userId:"actor"},body,params,query,ip:"127.0.0.1",get:()=>"test"};const res={status(c){out.status=c;return this},json(b){out.body=b;out.status||=200;return this}};await handler(req,res);return out}
const updateBody={studentNumber:"ST-002",fullName:"Updated Student",email:"UPDATED@example.test",programme:"Science"};
test("super admin views any student",async()=>assert.equal((await invoke(load().controller.getOne)).status,200));
test("institution roles view only own institution",async()=>{assert.equal((await invoke(load().controller.getOne,{role:"verifier",institutionId:INST})).status,200);assert.equal((await invoke(load({student:{institution_id:OTHER}}).controller.getOne,{role:"institution_admin",institutionId:INST})).status,403)});
test("unknown student returns 404",async()=>assert.equal((await invoke(load({student:null}).controller.getOne)).status,404));
test("student identity update normalizes data and audits old/new values",async()=>{const{controller,state}=load();const r=await invoke(controller.update,{body:updateBody});assert.equal(r.status,200);assert.equal(state.updates[0].email,"updated@example.test");assert.equal(state.audits[0].action,"STUDENT_UPDATED");assert.equal(state.audits[0].details.before.studentNumber,"ST-001")});
test("cross-institution update is denied",async()=>assert.equal((await invoke(load({student:{institution_id:OTHER}}).controller.update,{role:"issuer",institutionId:INST,body:updateBody})).status,403));
test("duplicate student number produces controlled conflict",async()=>{const{controller}=load({model:{updateStudent:async()=>{throw Object.assign(new Error(),{code:"23505"})}}});assert.equal((await invoke(controller.update,{body:updateBody})).status,409)});
test("super admin may reassign credential-free student to active institution",async()=>{const{controller,state}=load();const r=await invoke(controller.assignInstitution,{body:{institutionId:OTHER}});assert.equal(r.status,200);assert.deepEqual(state.updates[0],{institutionId:OTHER});assert.equal(state.audits[0].action,"STUDENT_INSTITUTION_REASSIGNED")});
test("credential history blocks reassignment without modifying it",async()=>{const{controller,state}=load({hasCredentials:true});assert.equal((await invoke(controller.assignInstitution,{body:{institutionId:OTHER}})).status,409);assert.equal(state.updates.length,0)});
test("inactive target institution and non-super actor are rejected",async()=>{assert.equal((await invoke(load({institutionActive:false}).controller.assignInstitution,{body:{institutionId:OTHER}})).status,422);assert.equal((await invoke(load().controller.assignInstitution,{role:"institution_admin",institutionId:INST,body:{institutionId:OTHER}})).status,403)});
test("schemas reject mass assignment, malformed IDs, and malformed student numbers",()=>{const schemas=require("../backend/validators/studentValidator");assert.equal(schemas.update.safeParse({...updateBody,institutionId:OTHER}).success,false);assert.equal(schemas.idParams.safeParse({id:"bad"}).success,false);assert.equal(schemas.update.safeParse({...updateBody,studentNumber:"ST 002"}).success,false)});
test("student SQL is parameterized and credential history is read-only",()=>{const source=require("fs").readFileSync(require.resolve("../backend/models/studentModel"),"utf8");assert.match(source,/WHERE student_id=\$1/);assert.match(source,/UPDATE students SET student_number=\$2/);assert.doesNotMatch(source,/UPDATE credentials/)});
test("schema has no status lifecycle and credentials restrict student deletion",()=>{const schema=require("fs").readFileSync(require("path").resolve(__dirname,"../backend/database/migrations/000_initial_schema.sql"),"utf8");assert.doesNotMatch(schema,/CREATE TABLE IF NOT EXISTS students[\s\S]*?is_active[\s\S]*?CREATE TABLE IF NOT EXISTS credentials/);assert.match(schema,/student_id UUID NOT NULL REFERENCES students\(id\) ON DELETE RESTRICT/)});
