const test = require("node:test");
const assert = require("node:assert/strict");
const crypto = require("node:crypto");

const ID = "11111111-1111-4111-8111-111111111111";
const OTHER = "22222222-2222-4222-8222-222222222222";
const INST = "33333333-3333-4333-8333-333333333333";
const OTHER_INST = "44444444-4444-4444-8444-444444444444";
const baseUser = { id: ID, full_name: "Managed User", email: "user@example.test", password_hash: "HASH", role: "issuer", institution_id: INST, is_active: true, must_change_password: false, token_version: 2, created_at: new Date() };

const loadUserController = (overrides = {}) => {
  const paths = { controller: require.resolve("../backend/controllers/userController"), model: require.resolve("../backend/models/userModel"), institution: require.resolve("../backend/models/institutionModel"), audit: require.resolve("../backend/models/auditModel"), bcrypt: require.resolve("bcryptjs") };
  Object.values(paths).forEach((p) => delete require.cache[p]);
  const state = { audits: [], updates: [], resets: [], users: [baseUser] };
  const model = {
    createUser: async (data) => ({ ...baseUser, id: OTHER, full_name: data.fullName, email: data.email, role: data.role, institution_id: data.institutionId, must_change_password: true }),
    findUserByEmail: async () => null,
    findUserForAuthentication: async (id) => id === "missing" ? null : ({ ...baseUser, id, ...(overrides.target || {}) }),
    findSafeUserById: async (id) => ({ ...baseUser, id, ...(overrides.target || {}) }),
    listUsers: async ({ institutionId }) => state.users.filter((u) => !institutionId || u.institution_id === institutionId),
    updateUserFields: async (id, fields) => { state.updates.push(fields); return { ...baseUser, id, full_name: fields.fullName || baseUser.full_name, email: fields.email || baseUser.email }; },
    updateUserStatus: async (id, isActive) => { state.updates.push({ isActive }); return { ...baseUser, id, is_active: isActive }; },
    updateUserRole: async (id, role) => { state.updates.push({ role }); return { ...baseUser, id, role }; },
    updateUserRoleAndInstitution: async (id, role, institutionId) => { state.updates.push({ role, institutionId }); return { ...baseUser, id, role, institution_id: institutionId }; },
    updateUserInstitution: async (id, institutionId) => { state.updates.push({ institutionId }); return { ...baseUser, id, institution_id: institutionId }; },
    unlockUser: async (id) => { state.updates.push({ unlock: true }); return { ...baseUser, id, is_locked: false }; },
    requireUserPasswordChange: async (id) => { state.updates.push({ mustChangePassword: true }); return { ...baseUser, id, must_change_password: true }; },
    updateUserPassword: async (id, hash) => { state.updates.push({ passwordHash: hash }); return { id, token_version: 3 }; },
    setPasswordReset: async (id, hash, expiresAt) => { state.resets.push({ id, hash, expiresAt }); return { id }; },
    countActiveSuperAdmins: async () => overrides.activeSuperAdmins ?? 2,
    ...overrides.model,
  };
  require.cache[paths.model] = { id: paths.model, filename: paths.model, loaded: true, exports: model };
  require.cache[paths.institution] = { id: paths.institution, filename: paths.institution, loaded: true, exports: { getInstitutionById: async (id) => id === "missing" ? null : ({ id, status: overrides.institutionActive !== false }) } };
  require.cache[paths.audit] = { id: paths.audit, filename: paths.audit, loaded: true, exports: { createAuditLog: async (entry) => state.audits.push(entry) } };
  require.cache[paths.bcrypt] = { id: paths.bcrypt, filename: paths.bcrypt, loaded: true, exports: { hash: async (value) => `hashed:${value}`, compare: async (value, hash) => hash === `hashed:${value}` || (hash === "HASH" && value === "Current1!Password") } };
  return { controller: require(paths.controller), state, paths };
};
const invoke = async (handler, { role = "super_admin", institutionId = null, userId = OTHER, params = { id: ID }, body = {}, query = {} } = {}) => {
  const result = {}; const req = { params, body, query, user: { userId, role, institutionId, tokenVersion: 2, currentUser: { ...baseUser, id: userId, role, institution_id: institutionId, password_hash: "HASH" } }, ip: "127.0.0.1", get: () => "test" };
  const res = { status(code) { result.status = code; return this; }, json(payload) { result.body = payload; if (!result.status) result.status = 200; return this; } };
  await handler(req, res); return result;
};

test("super admin lists all users", async () => { const { controller } = loadUserController(); assert.equal((await invoke(controller.list)).body.total, 1); });
test("institution admin list is scoped", async () => { const { controller, state } = loadUserController(); state.users.push({ ...baseUser, id: OTHER, institution_id: OTHER_INST }); assert.equal((await invoke(controller.list, { role: "institution_admin", institutionId: INST })).body.total, 1); });
test("issuer and verifier are denied by user route role middleware", () => { const router = require("../backend/routes/userRoutes"); const role = router.stack[2].handle; for (const value of ["issuer", "verifier"]) { const out = {}; role({ user: { role: value } }, { status(c) { out.code = c; return this; }, json() {} }, () => {}); assert.equal(out.code, 403); } });
test("super admin views any user safely", async () => { const { controller } = loadUserController(); const r = await invoke(controller.getOne); assert.equal(r.status, 200); assert.equal(r.body.user.password_hash, undefined); });
test("institution admin cannot view another institution user", async () => { const { controller } = loadUserController({ target: { institution_id: OTHER_INST } }); assert.equal((await invoke(controller.getOne, { role: "institution_admin", institutionId: INST })).status, 403); });

for (const role of ["institution_admin", "issuer"]) test(`super admin creates ${role}`, async () => { const { controller, state } = loadUserController(); const r = await invoke(controller.create, { body: { fullName: "New User", email: `${role}@example.test`, role, institutionId: INST } }); assert.equal(r.status, 201); assert.equal(state.resets.length, 1); });
for (const role of ["issuer", "verifier"]) test(`institution admin creates ${role} in own institution`, async () => { const { controller } = loadUserController(); assert.equal((await invoke(controller.create, { role: "institution_admin", institutionId: INST, body: { fullName: "New User", email: `${role}@example.test`, role, institutionId: OTHER_INST } })).status, 201); });
test("institution admin cannot create super admin", async () => { const { controller } = loadUserController(); assert.equal((await invoke(controller.create, { role: "institution_admin", institutionId: INST, body: { fullName: "New User", email: "new@example.test", role: "super_admin" } })).status, 403); });
test("duplicate email is rejected", async () => { const { controller } = loadUserController({ model: { findUserByEmail: async () => baseUser } }); assert.equal((await invoke(controller.create, { body: { fullName: "New User", email: "new@example.test", role: "issuer", institutionId: INST } })).status, 409); });
test("invalid and inactive institutions are rejected", async () => { const first = loadUserController(); assert.equal((await invoke(first.controller.create, { body: { fullName: "New User", email: "new@example.test", role: "issuer", institutionId: "bad" } })).status, 400); const second = loadUserController({ institutionActive: false }); assert.equal((await invoke(second.controller.create, { body: { fullName: "New User", email: "new@example.test", role: "issuer", institutionId: INST } })).status, 422); });
test("safe update allows identity fields", async () => { const { controller, state } = loadUserController(); assert.equal((await invoke(controller.update, { body: { fullName: "Changed" } })).status, 200); assert.deepEqual(state.updates[0], { fullName: "Changed" }); });
test("mass assignment is rejected", async () => { const { controller, state } = loadUserController(); assert.equal((await invoke(controller.update, { body: { role: "super_admin", isActive: true } })).status, 400); assert.equal(state.updates.length, 0); });
test("activation and deactivation work and audit", async () => { const { controller, state } = loadUserController(); assert.equal((await invoke(controller.changeStatus, { body: { isActive: false } })).status, 200); assert.equal(state.audits.at(-1).action, "USER_DEACTIVATED"); assert.equal((await invoke(controller.changeStatus, { body: { isActive: true } })).status, 200); });
test("institution admin cannot deactivate cross-institution user", async () => { const { controller } = loadUserController({ target: { institution_id: OTHER_INST } }); assert.equal((await invoke(controller.changeStatus, { role: "institution_admin", institutionId: INST, body: { isActive: false } })).status, 403); });
test("last active super admin cannot be deactivated", async () => { const { controller } = loadUserController({ target: { role: "super_admin" }, activeSuperAdmins: 1 }); assert.equal((await invoke(controller.changeStatus, { userId: OTHER, body: { isActive: false } })).status, 409); });
test("role change works and invalid role is rejected", async () => { const { controller, state } = loadUserController(); assert.equal((await invoke(controller.changeRole, { body: { role: "verifier" } })).status, 200); assert.equal(state.audits.at(-1).action, "USER_ROLE_CHANGED"); assert.equal((await invoke(controller.changeRole, { body: { role: "root" } })).status, 400); });
test("institution admin cannot promote super admin", async () => { const { controller } = loadUserController(); assert.equal((await invoke(controller.changeRole, { role: "institution_admin", institutionId: INST, body: { role: "super_admin" } })).status, 403); });
test("only super admin can reassign institutions", async () => { const first = loadUserController(); assert.equal((await invoke(first.controller.assignInstitution, { body: { institutionId: OTHER_INST } })).status, 200); const second = loadUserController(); assert.equal((await invoke(second.controller.assignInstitution, { role: "institution_admin", institutionId: INST, body: { institutionId: OTHER_INST } })).status, 403); });
test("profile is safe and profile update cannot change role", async () => { const { controller } = loadUserController(); const profile = await invoke(controller.profile); assert.equal(profile.body.user.passwordHash, undefined); assert.equal((await invoke(controller.updateProfile, { body: { role: "super_admin" } })).status, 400); });
test("password change validates current password, strength, match and reuse", async () => { const one = loadUserController(); assert.equal((await invoke(one.controller.changePassword, { body: { newPassword: "NewSecure1!Pass", confirmPassword: "NewSecure1!Pass" } })).status, 400); const two = loadUserController(); assert.equal((await invoke(two.controller.changePassword, { body: { currentPassword: "wrong", newPassword: "NewSecure1!Pass", confirmPassword: "NewSecure1!Pass" } })).status, 401); const three = loadUserController(); assert.equal((await invoke(three.controller.changePassword, { body: { currentPassword: "Current1!Password", newPassword: "weak", confirmPassword: "weak" } })).status, 400); const four = loadUserController(); assert.equal((await invoke(four.controller.changePassword, { body: { currentPassword: "Current1!Password", newPassword: "NewSecure1!Pass", confirmPassword: "different" } })).status, 400); const five = loadUserController(); assert.equal((await invoke(five.controller.changePassword, { body: { currentPassword: "Current1!Password", newPassword: "Current1!Password", confirmPassword: "Current1!Password" } })).status, 409); });
test("new password is hashed, token version update delegated, and audited", async () => { const { controller, state } = loadUserController(); assert.equal((await invoke(controller.changePassword, { body: { currentPassword: "Current1!Password", newPassword: "NewSecure1!Pass", confirmPassword: "NewSecure1!Pass" } })).status, 200); assert.match(state.updates[0].passwordHash, /^hashed:/); assert.equal(state.audits.at(-1).action, "PASSWORD_CHANGED"); });
test("admin reset stores only SHA-256 hash and omits raw token from audit", async () => { const { controller, state } = loadUserController(); const r = await invoke(controller.resetPassword); assert.equal(r.status, 200); assert.match(state.resets[0].hash, /^[a-f0-9]{64}$/); assert.notEqual(state.resets[0].hash, r.body.developmentResetToken); assert.equal(JSON.stringify(state.audits).includes(r.body.developmentResetToken), false); });
test("admin reset never returns a raw token or generated password", async () => { const { controller }=loadUserController(); const r=await invoke(controller.resetPassword); assert.equal(r.body.developmentResetToken,undefined); assert.equal(JSON.stringify(r.body).includes("password_hash"),false); });
test("unlock clears only lock state and audits the action",async()=>{const{controller,state}=loadUserController();const r=await invoke(controller.unlock);assert.equal(r.status,200);assert.deepEqual(state.updates[0],{unlock:true});assert.equal(state.audits.at(-1).action,"ACCOUNT_UNLOCKED");});
test("institution administrator cannot unlock across institutions",async()=>{const{controller}=loadUserController({target:{institution_id:OTHER_INST}});assert.equal((await invoke(controller.unlock,{role:"institution_admin",institutionId:INST})).status,403);});
test("requiring a password change invalidates sessions through the model and audits",async()=>{const{controller,state}=loadUserController();const r=await invoke(controller.requirePasswordChange);assert.equal(r.status,200);assert.equal(r.body.user.mustChangePassword,true);assert.deepEqual(state.updates[0],{mustChangePassword:true});assert.equal(state.audits.at(-1).action,"PASSWORD_CHANGE_REQUIRED");});
test("safe detail exposes bounded status but no counters, hashes, or token version",async()=>{const{controller}=loadUserController({target:{is_locked:true,last_login_at:new Date()}});const body=(await invoke(controller.getOne)).body.user;assert.equal(body.isLocked,true);for(const key of ["failed_login_attempts","locked_until","password_hash","password_reset_token_hash","token_version"])assert.equal(body[key],undefined);});
test("identity audit records safe before and after values",async()=>{const{controller,state}=loadUserController();await invoke(controller.update,{body:{fullName:"Changed",email:"changed@example.test"}});assert.deepEqual(state.audits.at(-1).details.before,{fullName:"Managed User",email:"user@example.test"});assert.deepEqual(state.audits.at(-1).details.after,{fullName:"Changed",email:"changed@example.test"});});

test("current-user middleware rejects stale and deactivated tokens", async () => {
  const modelPath = require.resolve("../backend/models/userModel"); const middlewarePath = require.resolve("../backend/middleware/authMiddleware");
  for (const [user, expected] of [[{ ...baseUser, token_version: 3 }, 401], [{ ...baseUser, is_active: false }, 403]]) { require.cache[modelPath] = { id: modelPath, filename: modelPath, loaded: true, exports: { findUserForAuthentication: async () => user } }; delete require.cache[middlewarePath]; const middleware = require(middlewarePath).requireCurrentUser; const out = {}; await middleware({ user: { userId: ID, tokenVersion: 2 } }, { status(c) { out.code = c; return this; }, json() {} }, () => { out.next = true; }); assert.equal(out.code, expected); }
  delete require.cache[middlewarePath]; delete require.cache[modelPath];
});

test("public registration is disabled and cannot provision any role", () => { const source = require("node:fs").readFileSync(require("node:path").resolve(__dirname, "../backend/controllers/authController.js"), "utf8"); assert.match(source, /PUBLIC_REGISTRATION_DISABLED/); assert.doesNotMatch(source, /role: ROLES\.VERIFIER/); });
test("reset tokens use cryptographic randomness and only their hash reaches persistence", () => { const source = require("node:fs").readFileSync(require("node:path").resolve(__dirname, "../backend/controllers/userController.js"), "utf8"); assert.match(source, /crypto\.randomBytes\(32\)/); assert.match(source, /createHash\("sha256"\)/); });

test("super admin creation discards institution scope", async () => { const { controller, state } = loadUserController(); await invoke(controller.create, { body: { fullName: "Global Admin", email: "global@example.test", role: "super_admin", institutionId: INST } }); assert.equal(state.resets.length, 1); assert.equal(state.audits.at(-1).details.institutionId, null); });
test("self role change is forbidden", async () => { const { controller } = loadUserController(); assert.equal((await invoke(controller.changeRole, { userId: ID, body: { role: "super_admin" } })).status, 409); });
test("promotion to super admin clears stale institution and invalidates through model", async () => { const { controller, state } = loadUserController(); assert.equal((await invoke(controller.changeRole, { body: { role: "super_admin" } })).status, 200); assert.deepEqual(state.updates[0], { role: "super_admin", institutionId: null }); });
test("scoped role change requires an active institution", async () => { const first=loadUserController({target:{role:"super_admin",institution_id:null},activeSuperAdmins:2}); assert.equal((await invoke(first.controller.changeRole,{body:{role:"issuer"}})).status,422); const second=loadUserController({target:{role:"super_admin",institution_id:null},activeSuperAdmins:2,institutionActive:false}); assert.equal((await invoke(second.controller.changeRole,{body:{role:"issuer",institutionId:INST}})).status,422); });
test("last active super admin cannot be demoted", async () => { const {controller}=loadUserController({target:{role:"super_admin",institution_id:null},activeSuperAdmins:1}); assert.equal((await invoke(controller.changeRole,{body:{role:"issuer",institutionId:INST}})).status,409); });
test("global super admin cannot be assigned to an institution", async () => { const {controller}=loadUserController({target:{role:"super_admin",institution_id:null}}); assert.equal((await invoke(controller.assignInstitution,{body:{institutionId:INST}})).status,409); });
test("inactive and unassigned institution accounts are rejected centrally", async () => { const modelPath=require.resolve("../backend/models/userModel"), middlewarePath=require.resolve("../backend/middleware/authMiddleware"); for(const current of [{...baseUser,institution_active:false},{...baseUser,institution_id:null,institution_active:null}]){require.cache[modelPath]={id:modelPath,filename:modelPath,loaded:true,exports:{findUserForAuthentication:async()=>current}};delete require.cache[middlewarePath];const out={};await require(middlewarePath).requireCurrentUser({user:{userId:ID,tokenVersion:2}},{status(c){out.code=c;return this},json(b){out.body=b}},()=>{out.next=true});assert.equal(out.code,403);assert.equal(out.body.code,"INSTITUTION_ACCESS_INACTIVE");}delete require.cache[middlewarePath];delete require.cache[modelPath]; });
test("forced-change middleware permits only profile, change-password, and logout", async () => { const modelPath=require.resolve("../backend/models/userModel"),middlewarePath=require.resolve("../backend/middleware/authMiddleware");require.cache[modelPath]={id:modelPath,filename:modelPath,loaded:true,exports:{findUserForAuthentication:async()=>({...baseUser,role:"super_admin",institution_id:null,must_change_password:true,token_version:2})}};delete require.cache[middlewarePath];const middleware=require(middlewarePath).requireCurrentUser;for(const [baseUrl,path,allowed] of [["/api/auth","/profile",true],["/api/auth","/change-password",true],["/api/auth","/logout",true],["/api/dashboard","/summary",false]]){const out={};await middleware({baseUrl,path,user:{userId:ID,tokenVersion:2}},{status(c){out.status=c;return this},json(b){out.body=b}},()=>{out.next=true});assert.equal(Boolean(out.next),allowed);if(!allowed){assert.equal(out.status,403);assert.equal(out.body.code,"PASSWORD_CHANGE_REQUIRED");}}delete require.cache[middlewarePath];delete require.cache[modelPath];});
test("password model clears forced-change state and invalidates sessions without changing role or institution",()=>{const source=require("fs").readFileSync(require.resolve("../backend/models/userModel"),"utf8");const statement=source.match(/const updateUserPassword[\s\S]*?return result\.rows\[0\];/)[0];assert.match(statement,/must_change_password = FALSE/);assert.match(statement,/token_version = token_version \+ 1/);assert.doesNotMatch(statement,/role\s*=|institution_id\s*=/);});
