const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { validate } = require("../backend/middleware/validationMiddleware");
const common = require("../backend/validators/commonValidator");
const auth = require("../backend/validators/authValidator");
const users = require("../backend/validators/userValidator");
const institutions = require("../backend/validators/institutionValidator");
const credentials = require("../backend/validators/credentialValidator");
const audit = require("../backend/validators/auditValidator");

const run = async (schemas, request) => { const out = {}; const res = { status(c) { out.status = c; return this; }, json(body) { out.body = body; return this; } }; await validate(schemas)(request, res, () => { out.next = true; }); return out; };
test("invalid UUID is rejected before controller execution", async () => { const out = await run({ params: users.idParams }, { params: { id: "bad" } }); assert.equal(out.status, 400); assert.equal(out.next, undefined); });
test("invalid email is rejected", () => assert.equal(common.email.safeParse("bad").success, false));
test("invalid role is rejected", () => assert.equal(common.role.safeParse("root").success, false));
test("invalid and zero EVM wallets are rejected", () => { assert.equal(common.wallet.safeParse("bad").success, false); assert.equal(common.wallet.safeParse("0x0000000000000000000000000000000000000000").success, false); });
test("invalid SHA-256 is rejected and controlled prefix is normalized", () => { assert.equal(common.sha256.safeParse("abc").success, false); assert.equal(common.sha256.parse(`0x${"A".repeat(64)}`), "a".repeat(64)); });
test("invalid public token is rejected", () => assert.equal(common.publicToken.safeParse("token-1").success, false));
test("invalid ISO date and reversed credential range are rejected", () => { assert.equal(common.isoDate.safeParse("03/04/2026").success, false); assert.equal(credentials.listQuery.safeParse({ issueDateFrom: "2026-08-04", issueDateTo: "2026-08-03" }).success, false); });
test("invalid audit date range is rejected", () => assert.equal(audit.listQuery.safeParse({ dateFrom: "2026-08-04", dateTo: "2026-08-03" }).success, false));
test("invalid sort field and order are rejected", () => { assert.equal(audit.listQuery.safeParse({ sortBy: "raw_sql" }).success, false); assert.equal(audit.listQuery.safeParse({ sortOrder: "sideways" }).success, false); });
test("negative page and excessive limit are rejected", () => { assert.equal(users.listQuery.safeParse({ page: "-1" }).success, false); assert.equal(users.listQuery.safeParse({ limit: "101" }).success, false); });
test("weak and whitespace-padded passwords are rejected", () => { assert.equal(auth.strongPassword.safeParse("weak").success, false); assert.equal(auth.strongPassword.safeParse(" StrongSecure1!Pass ").success, false); });
test("password mismatch is rejected", () => assert.equal(auth.changePassword.safeParse({ currentPassword: "Current1!Pass", newPassword: "NewSecure1!Pass", confirmPassword: "OtherSecure1!Pass" }).success, false));
test("unknown sensitive fields are rejected", () => assert.equal(users.update.safeParse({ fullName: "Safe Name", token_version: 999, password_hash: "x" }).success, false));
test("privileged public registration role is rejected", () => assert.equal(auth.register.safeParse({ fullName: "Safe Name", email: "safe@example.test", password: "StrongSecure1!Pass", role: "super_admin" }).success, false));
test("valid existing institution request succeeds", () => assert.equal(institutions.create.safeParse({ name: "Safe Institution", email: "safe@example.test", walletAddress: "0x0000000000000000000000000000000000000001" }).success, true));
test("validation response shape is consistent", async () => { const out = await run({ body: auth.login }, { body: { email: "bad", password: "" } }); assert.equal(out.body.code, "VALIDATION_ERROR"); assert.equal(Array.isArray(out.body.errors), true); assert.deepEqual(Object.keys(out.body.errors[0]).sort(), ["field", "message"]); });
test("temporary uploaded file is removed after validation failure", async () => { const dir = await fs.promises.mkdtemp(path.join(os.tmpdir(), "validation-cleanup-")); const file = path.join(dir, "upload.pdf"); await fs.promises.writeFile(file, "%PDF"); try { await run({ body: credentials.issue }, { body: {}, file: { path: file } }); assert.equal(fs.existsSync(file), false); } finally { await fs.promises.rm(dir, { recursive: true, force: true }); } });
