const express = require("express");
const { authenticate, requireCurrentUser, authorizeRoles } = require("../middleware/authMiddleware");
const controller = require("../controllers/userController");
const router = express.Router();
const { validate } = require("../middleware/validationMiddleware");
const schemas = require("../validators/userValidator");
const { adminActionLimiter, passwordResetLimiter, sensitiveNoStore } = require("../middleware/securityMiddleware");
router.use(authenticate, requireCurrentUser, authorizeRoles("super_admin", "institution_admin"));
router.use(sensitiveNoStore);
router.get("/", validate({ query: schemas.listQuery }), controller.list);
router.get("/:id", validate({ params: schemas.idParams }), controller.getOne);
router.post("/", validate({ body: schemas.create }), controller.create);
router.patch("/:id", validate({ params: schemas.idParams, body: schemas.update }), controller.update);
router.patch("/:id/status", adminActionLimiter, validate({ params: schemas.idParams, body: schemas.status }), controller.changeStatus);
router.patch("/:id/role", adminActionLimiter, validate({ params: schemas.idParams, body: schemas.roleChange }), controller.changeRole);
router.patch("/:id/institution", adminActionLimiter, validate({ params: schemas.idParams, body: schemas.institution }), controller.assignInstitution);
router.post("/:id/unlock", adminActionLimiter, validate({ params: schemas.idParams, body: schemas.action }), controller.unlock);
router.post("/:id/require-password-change", adminActionLimiter, validate({ params: schemas.idParams, body: schemas.action }), controller.requirePasswordChange);
router.post("/:id/reset-password", passwordResetLimiter, adminActionLimiter, validate({ params: schemas.idParams, body: schemas.reset }), controller.resetPassword);
module.exports = router;
