import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { MemoryRouter, Route, Routes } from 'react-router-dom';
import { beforeEach, describe, expect, it, vi } from 'vitest';
import { api } from '../api/client';
import { AuthProvider, useAuth } from '../context/AuthContext';
import { ChangePassword, ForgotPasswordPage, LoginPage, ResetPasswordPage } from '../pages/AuthPages';
vi.mock('../api/client',()=>({api:{get:vi.fn(),post:vi.fn()}}));

function Probe(){const a=useAuth();return <><span>{a.user?.email||'signed-out'}</span><button onClick={()=>void a.login('admin@example.test','ValidPass1!')}>login</button><button onClick={()=>void a.logout()}>logout</button></>}
describe('authentication lifecycle',()=>{
  beforeEach(()=>vi.clearAllMocks());
  it('successful login uses safe returned user without persisting a token',async()=>{vi.mocked(api.post).mockResolvedValue({data:{user:{email:'admin@example.test'}}});vi.mocked(api.get).mockRejectedValue(new Error('anonymous'));render(<AuthProvider><Probe/></AuthProvider>);fireEvent.click(screen.getByText('login'));await waitFor(()=>expect(screen.getByText('admin@example.test')).toBeInTheDocument())});
  it('logout calls API and clears authenticated state',async()=>{vi.mocked(api.get).mockResolvedValue({data:{user:{email:'admin@example.test'}}});vi.mocked(api.post).mockResolvedValue({data:{}});render(<AuthProvider><Probe/></AuthProvider>);await screen.findByText('admin@example.test');fireEvent.click(screen.getByText('logout'));await waitFor(()=>expect(screen.getByText('signed-out')).toBeInTheDocument());expect(api.post).toHaveBeenCalledWith('/auth/logout')});
  it('profile hydration and expired session events control rendered state',async()=>{vi.mocked(api.get).mockResolvedValue({data:{user:{email:'admin@example.test'}}});render(<AuthProvider><Probe/></AuthProvider>);await screen.findByText('admin@example.test');window.dispatchEvent(new Event('session-expired'));await waitFor(()=>expect(screen.getByText('signed-out')).toBeInTheDocument())});
  it('login form validates invalid email and missing password',async()=>{render(<MemoryRouter><AuthProvider><LoginPage/></AuthProvider></MemoryRouter>);fireEvent.change(screen.getByLabelText('Email address'),{target:{value:'bad'}});fireEvent.submit(screen.getByText('Sign in').closest('form')!);expect(await screen.findByText('Enter a valid email address.')).toBeInTheDocument();expect(api.post).not.toHaveBeenCalled()});
  it('invalid login shows normalized safe error',async()=>{vi.mocked(api.post).mockRejectedValue({message:'Invalid email or password.'});render(<MemoryRouter><AuthProvider><LoginPage/></AuthProvider></MemoryRouter>);fireEvent.change(screen.getByLabelText('Email address'),{target:{value:'admin@example.test'}});fireEvent.change(screen.getByLabelText('Password'),{target:{value:'wrong'}});fireEvent.click(screen.getByText('Sign in'));expect(await screen.findByRole('alert')).toHaveTextContent('Invalid email or password.')});
  it('forced password change redirects to the supported page',async()=>{vi.mocked(api.get).mockRejectedValue(new Error('anonymous'));vi.mocked(api.post).mockResolvedValue({data:{user:{email:'admin@example.test',mustChangePassword:true}}});render(<MemoryRouter initialEntries={['/login']}><AuthProvider><Routes><Route path="/login" element={<LoginPage/>}/><Route path="/app/change-password" element={<p>Forced password page</p>}/></Routes></AuthProvider></MemoryRouter>);fireEvent.change(screen.getByLabelText('Email address'),{target:{value:'admin@example.test'}});fireEvent.change(screen.getByLabelText('Password'),{target:{value:'ValidPass1!'}});fireEvent.click(screen.getByText('Sign in'));expect(await screen.findByText('Forced password page')).toBeInTheDocument()});
  it('forced password change sends the strict payload, clears auth state, and redirects to login',async()=>{vi.mocked(api.get).mockResolvedValue({data:{user:{email:'admin@example.test',role:'super_admin',institutionId:null,mustChangePassword:true}}});vi.mocked(api.post).mockResolvedValue({data:{success:true}});render(<MemoryRouter initialEntries={['/app/change-password']}><AuthProvider><Routes><Route path="/app/change-password" element={<ChangePassword/>}/><Route path="/login" element={<LoginPage/>}/></Routes></AuthProvider></MemoryRouter>);fireEvent.change(await screen.findByLabelText('Current password'),{target:{value:'CurrentSecure1!'}});fireEvent.change(screen.getByLabelText('New password'),{target:{value:'NewSecurePass1!'}});fireEvent.change(screen.getByLabelText('Confirm new password'),{target:{value:'NewSecurePass1!'}});fireEvent.click(screen.getByRole('button',{name:'Update password'}));expect(await screen.findByText('Password changed successfully. Please sign in again.')).toBeInTheDocument();expect(api.post).toHaveBeenCalledWith('/auth/change-password',{currentPassword:'CurrentSecure1!',newPassword:'NewSecurePass1!',confirmPassword:'NewSecurePass1!'});});
  it('forced password change surfaces controlled backend errors',async()=>{vi.mocked(api.get).mockResolvedValue({data:{user:{email:'admin@example.test',role:'super_admin',institutionId:null,mustChangePassword:true}}});vi.mocked(api.post).mockRejectedValue({message:'Current password is incorrect.'});render(<MemoryRouter><AuthProvider><ChangePassword/></AuthProvider></MemoryRouter>);fireEvent.change(await screen.findByLabelText('Current password'),{target:{value:'WrongSecure1!'}});fireEvent.change(screen.getByLabelText('New password'),{target:{value:'NewSecurePass1!'}});fireEvent.change(screen.getByLabelText('Confirm new password'),{target:{value:'NewSecurePass1!'}});fireEvent.click(screen.getByRole('button',{name:'Update password'}));expect(await screen.findByRole('alert')).toHaveTextContent('Current password is incorrect.');});
  it('forced password change validates policy before submission',async()=>{vi.mocked(api.get).mockResolvedValue({data:{user:{email:'admin@example.test',role:'super_admin',institutionId:null,mustChangePassword:true}}});render(<MemoryRouter><AuthProvider><ChangePassword/></AuthProvider></MemoryRouter>);fireEvent.change(await screen.findByLabelText('Current password'),{target:{value:'CurrentSecure1!'}});fireEvent.change(screen.getByLabelText('New password'),{target:{value:'weak'}});fireEvent.change(screen.getByLabelText('Confirm new password'),{target:{value:'different'}});fireEvent.click(screen.getByRole('button',{name:'Update password'}));expect(await screen.findByText('Use at least 12 characters.')).toBeInTheDocument();expect(api.post).not.toHaveBeenCalled();});
});
describe('password recovery',()=>{
  beforeEach(()=>vi.clearAllMocks());
  it('submits forgot-password and always presents the generic response',async()=>{vi.mocked(api.post).mockResolvedValue({data:{success:true,message:'If an account exists for that email, password reset instructions have been sent.'}});render(<MemoryRouter><ForgotPasswordPage/></MemoryRouter>);fireEvent.change(screen.getByLabelText('Email address'),{target:{value:'person@example.com'}});fireEvent.submit(screen.getByRole('button',{name:/send reset/i}).closest('form')!);expect(await screen.findByText(/if an account exists/i)).toBeInTheDocument();expect(api.post).toHaveBeenCalledWith('/auth/forgot-password',{email:'person@example.com'});});
  it('validates forgot-password email locally',async()=>{render(<MemoryRouter><ForgotPasswordPage/></MemoryRouter>);fireEvent.change(screen.getByLabelText('Email address'),{target:{value:'bad'}});fireEvent.submit(screen.getByRole('button',{name:/send reset/i}).closest('form')!);expect(await screen.findByText(/valid email/i)).toBeInTheDocument();expect(api.post).not.toHaveBeenCalled();});
  it('uses the reset token once, clears it from the visible URL, and shows success',async()=>{window.history.replaceState({},'', '/reset-password?token=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQ');vi.mocked(api.post).mockResolvedValue({data:{success:true,message:'Password reset successfully.'}});render(<MemoryRouter initialEntries={['/reset-password?token=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQ']}><ResetPasswordPage/></MemoryRouter>);fireEvent.change(screen.getByLabelText('New password'),{target:{value:'NewSecurePass1!'}});fireEvent.change(screen.getByLabelText('Confirm password'),{target:{value:'NewSecurePass1!'}});fireEvent.submit(screen.getByRole('button',{name:/reset password/i}).closest('form')!);expect(await screen.findByText(/password reset successfully/i)).toBeInTheDocument();expect(window.location.search).toBe('');});
  it('shows invalid or expired reset errors without authenticating',async()=>{vi.mocked(api.post).mockRejectedValue({message:'The password reset link is invalid or expired.'});render(<MemoryRouter initialEntries={['/reset-password?token=abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQ']}><ResetPasswordPage/></MemoryRouter>);fireEvent.change(screen.getByLabelText('New password'),{target:{value:'NewSecurePass1!'}});fireEvent.change(screen.getByLabelText('Confirm password'),{target:{value:'NewSecurePass1!'}});fireEvent.submit(screen.getByRole('button',{name:/reset password/i}).closest('form')!);expect(await screen.findByRole('alert')).toHaveTextContent(/invalid or expired/i);});
});
