require("dotenv").config({ quiet: true });
const crypto = require("crypto"); const fs = require("fs"); const path = require("path"); const zlib = require("zlib");
const { timestamp, resolveInside } = require("./recoveryUtils");
const DEFAULT_GROUPS = ["backend/uploads", "output/pdf", "generated/qr", "deployments", "backend/blockchain", "docs"];
const excluded = (relative) => /(^|[\\/])(node_modules|coverage|logs|test-results|certificates-temp)([\\/]|$)/i.test(relative) || /(^|[\\/])\.env(?:\.|$)/i.test(relative);
const walk = (root, relative, output) => { const absolute = resolveInside(root, relative); if (!fs.existsSync(absolute)) return; const stat = fs.statSync(absolute); if (stat.isDirectory()) return fs.readdirSync(absolute).sort().forEach((name) => walk(root, path.join(relative, name), output)); if (stat.isFile() && !excluded(relative)) output.push(relative.replace(/\\/g, "/")); };
const backupFiles = async (options = {}) => { const root = path.resolve(options.root || process.cwd()); const directory = path.resolve(options.directory || process.env.BACKUP_DIRECTORY || "backups/files"); fs.mkdirSync(directory, { recursive: true }); const id = `files_${timestamp(options.now)}`; const archivePath = path.join(directory, `${id}.json.gz`); const manifestPath = path.join(directory, `${id}.manifest.json`); if (fs.existsSync(archivePath)) throw new Error("File backup already exists."); const files=[]; for(const group of options.groups || DEFAULT_GROUPS) { if (excluded(group)) continue; walk(root, group, files); } const entries=[]; for(const relative of files){ const bytes=fs.readFileSync(resolveInside(root,relative)); entries.push({path:relative,size:bytes.length,sha256:crypto.createHash("sha256").update(bytes).digest("hex"),data:bytes.toString("base64")}); } const compressed=zlib.gzipSync(Buffer.from(JSON.stringify({version:1,entries}))); fs.writeFileSync(archivePath,compressed,{flag:"wx"}); const archiveSha256=crypto.createHash("sha256").update(compressed).digest("hex"); const manifest={backupId:id,createdAt:new Date().toISOString(),archiveFilename:path.basename(archivePath),checksum:{algorithm:"SHA-256",sha256:archiveSha256},includedFileGroups:(options.groups||DEFAULT_GROUPS),encryption:{enabled:false,method:null},files:entries.map(({data,...entry})=>entry),verification:{status:"pending"}}; fs.writeFileSync(manifestPath,`${JSON.stringify(manifest,null,2)}\n`,{flag:"wx"}); return {archivePath,manifestPath,manifest}; };
if(require.main===module) backupFiles().then(({manifest})=>console.log(JSON.stringify({backupId:manifest.backupId,files:manifest.files.length}))).catch(error=>{console.error(error.message);process.exitCode=1});
module.exports={backupFiles,excluded,DEFAULT_GROUPS};
